baseURL = 'https://bruce48x.github.io/'
languageCode = 'zh-cn'
title = 'Bruce'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

themes = ['ritzy']

[module]
  [[module.imports]]
    path = 'ritzy'