baseURL = 'https://bruce48x.github.io/'
languageCode = 'zh-cn'
title = 'Bruce'
theme = ["PaperMod"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true

[params]
  # 启用目录
  ShowToc = true
  
  # 目录默认展开（可选）
  TocOpen = true